{% set name = "hatch-vcs" %}
{% set version = "0.3.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_vcs-{{ version }}.tar.gz
  sha256: cec5107cfce482c67f8bc96f18bbc320c9aa0d068180e14ad317bbee5a153fee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling >=0.21.0
    - pip
    - python >=3.7
  run:
    - hatchling >=0.21.0
    - python >=3.7
    - setuptools-scm

test:
  imports:
    - hatch_vcs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/hatch-vcs/
  summary: Hatch plugin for versioning with your preferred VCS
  dev_url: https://github.com/ofek/hatch-vcs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
